# Generated by Django 3.1.2 on 2020-10-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=55, unique=True)),
                ('last_name', models.CharField(max_length=55, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=15)),
                ('referral_code', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_is_preferred', models.BooleanField(default=False)),
                ('availabilty_type', models.CharField(choices=[('Telemedicine', 'Telemedicine'), ('In-Person', 'In-Person')], max_length=15)),
                ('person_consultation_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Regular', 'Regular')], max_length=10)),
                ('emergency_details', models.TextField(blank=True, null=True)),
                ('ambulance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_attribute', to='patient_care.searchattribute')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('occupation', models.CharField(max_length=25)),
                ('marital_status', models.CharField(max_length=15)),
                ('emergency_contact_person', models.CharField(max_length=50)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('habits', models.CharField(max_length=55)),
                ('physical_activity', models.CharField(max_length=55)),
                ('pre_existing_disease', models.CharField(max_length=55)),
                ('prior_surgeries_type', models.CharField(choices=[('General', 'General Surgery'), ('Plastic', 'Plastic Surgery'), ('Neuro', 'Neurosurgery')], max_length=8)),
                ('prior_surgeries_year', models.IntegerField()),
                ('allergies', models.CharField(max_length=50)),
                ('report', models.ImageField(blank=True, null=True, upload_to='patient/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='doctor/')),
                ('hospital', models.CharField(max_length=55)),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Endocrinologists', 'Endocrinologists'), ('Nephrologists', 'Nephrologists')], max_length=18)),
                ('experience', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('E', 'English'), ('G', 'Gujarati'), ('H', 'Hindi')], max_length=1)),
                ('location', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConformBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conform_booking', to='patient_care.bookdoctor')),
            ],
        ),
        migrations.AddField(
            model_name='bookdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor', to='patient_care.doctorprofile'),
        ),
        migrations.AddField(
            model_name='bookdoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_patient', to='patient_care.patientprofile'),
        ),
    ]
