# Generated by Django 3.1.2 on 2020-10-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=55, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('referral_code', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('photo', models.ImageField(upload_to='doctor/')),
                ('hospital', models.CharField(max_length=55)),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Endocrinologists', 'Endocrinologists'), ('Nephrologists', 'Nephrologists')], max_length=18)),
                ('experience', models.DateField()),
                ('degree', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('E', 'English'), ('G', 'Gujarati'), ('H', 'Hindi')], max_length=1)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('occupation', models.CharField(max_length=25)),
                ('marital_status', models.CharField(max_length=15)),
                ('emergency_contact_person', models.CharField(max_length=50)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('habits', models.CharField(max_length=55)),
                ('physical_activity', models.CharField(max_length=55)),
                ('pre_existing_disease', models.CharField(max_length=55)),
                ('prior_surgeries_type', models.CharField(choices=[('General', 'General Surgery'), ('Plastic', 'Plastic Surgery'), ('Neuro', 'Neurosurgery')], max_length=8)),
                ('prior_surgeries_year', models.IntegerField()),
                ('allergies', models.CharField(max_length=50)),
                ('report', models.ImageField(blank=True, null=True, upload_to='patient/')),
                ('mobile_verify', models.BooleanField(default=False)),
                ('email_verity', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_is_preferred', models.BooleanField(default=False)),
                ('availabilty_type', models.CharField(choices=[('Telemedicine', 'Telemedicine'), ('In-Person', 'In-Person')], max_length=15)),
                ('person_consultation_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Regular', 'Regular')], max_length=10)),
                ('emergency_details', models.TextField(blank=True, null=True)),
                ('ambulance', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor', to='patient_care.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
