# Generated by Django 3.1.2 on 2020-10-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='user',
            new_name='patient',
        ),
    ]
