# Generated by Django 3.1.2 on 2020-10-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0002_auto_20201007_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
