# Generated by Django 3.1.2 on 2020-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0003_auto_20201009_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='universal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
