# Generated by Django 3.1.2 on 2020-10-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0003_auto_20201007_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='email_verity',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='mobile_verify',
        ),
    ]
