# Generated by Django 3.1.2 on 2020-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0004_auto_20201007_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
