# Generated by Django 3.1.2 on 2020-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0004_user_universal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdoctor',
            name='availabilty_type',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='availabilty_type',
            field=models.CharField(choices=[('Telemedicine', 'Telemedicine'), ('In-Person', 'In-Person')], default='Telemedicine', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='habits',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Smoking', 'Smoking'), ('Tobacco', 'Tobacco'), ('None of this', 'None of this')], default='None of this', max_length=55),
        ),
    ]
