# Generated by Django 3.1.2 on 2020-10-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0005_auto_20201014_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
    ]
