# Generated by Django 3.1.2 on 2020-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0006_searchattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
