# Generated by Django 3.1.2 on 2020-10-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0006_auto_20201019_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchattributevalue',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='SearchAttribute',
        ),
        migrations.DeleteModel(
            name='SearchAttributeValue',
        ),
    ]
