# Generated by Django 3.1.2 on 2020-10-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0007_bookdoctor_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdoctor',
            name='amount',
        ),
    ]
