# Generated by Django 3.1.2 on 2020-10-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0007_auto_20201019_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformbooking',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
