# Generated by Django 3.1.2 on 2020-10-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0008_conformbooking_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConformBooking',
            new_name='ConfirmBooking',
        ),
    ]
