# Generated by Django 3.1.2 on 2020-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0009_auto_20201019_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='availabilty_type',
            field=models.CharField(choices=[('Telemedicine', 'Telemedicine'), ('In-Person', 'In-Person')], default='Telemedicine', max_length=15),
        ),
    ]
